### ISSUE TITLE
Localization tweaks

### ISSUE THREAD

**Issue by WTurunen** [opencredit/BadgeOS-Community-Add-on#25]
1) The textdomain is not loaded in line ./badgeos-community.php:40. Please change to
```php
load_plugin_textdomain( 'badgeos-community', false, dirname( plugin_basename( __FILE__ ) ) .'/languages/' );
```
2)  Please add localization support to ./includes/steps-ui.php:38. Eg. 
```php
$triggers['community_trigger'] = __( 'Community Activity', 'badgeos-community' );
```

**Comment by tw2113** [comment]
Closing as it looks like at some point, we merged in the changes needed, and forgot to close the ticket :D
