### ISSUE TITLE
badgeos-community.po in French

### ISSUE THREAD

**Issue by cyclingzealot** [opencredit/BadgeOS-Community-Add-on#49]
Before I start working on it, has anyone done a badgeos-community-fr_FR.po available to the public?

I can see there's been a conversation about it here: https://badgeos.org/support/forums/topic/translate/.  But I can't see a register option to that site.

**Comment by tw2113** [comment]
That forum thread was for a specific issue regarding the Activity Codes plugin, and not the Community Addon here.

If it's not in the languages folder in the repo, then we likely haven't received one, so it's open season if you want to take on the task. I know we'd appreciate the help.

**Comment by cyclingzealot** [comment]
Thanks.  I'll issue a pull request once I am done or partially done.
